"""Embed benchmark results (and a hand-written narrative) into the research report page.

    python tools/inject_bench.py outputs/benchmark/results.json outputs/benchmark/narrative.json ../policy_research.html
"""

import json
import sys
from datetime import date
from pathlib import Path


def main(results_path, narrative_path, html_path):
    res = json.loads(Path(results_path).read_text())
    nar = json.loads(Path(narrative_path).read_text())
    log = res["log"]
    ch = log["chosen"]
    payload = {
        "summary": log["summary"],
        "settings": log["settings"],
        "train_seeds": log["train_seeds"],
        "test_seeds": log["test_seeds"],
        "horizon": 365,
        "chosen_text": (f"π₂ᵗ cover {ch['age'][1]}, β {ch['age'][2]}; band b = {ch['band'][1]}; "
                        f"SAA K {ch['saa'][1]}, S {ch['saa'][2]}, θ {ch['saa'][3]}; nowcast q {ch['nowcast_q']}"),
        "verdict": nar["verdict"],
        "findings": nar["findings"],
        "generated": f"Results generated by perishnet.benchmark on {date.today().isoformat()}; "
                     f"{len(res['runs'])} simulation runs and {len(res['bounds'])} bound LPs.",
    }
    html = Path(html_path).read_text(encoding="utf-8")
    start = html.index('<script id="bench" type="application/json">') + len('<script id="bench" type="application/json">')
    end = html.index("</script>", start)
    blob = json.dumps(payload, ensure_ascii=False).replace("</", "<\\/")
    Path(html_path).write_text(html[:start] + blob + html[end:], encoding="utf-8")
    print(f"embedded {len(blob):,} characters into {html_path}")


if __name__ == "__main__":
    main(*sys.argv[1:4])
